//should be sorted alphabetically and needs to be updated

type PlantFamily = "Tomato" 
                | "Potato" 
                | "Pepper" 
                | "Eggplant" 
                | "Cucumber" 
                | "Squash" 
                | "Melon" 
                | "Pumpkin" 
                | "Corn" 
                | "Bean" 
                | "Pea" 
                | "Lettuce" 
                | "Spinach" 
                | "Kale" 
                | "Chard" 
                | "Broccoli" 
                | "Cauliflower" 
                | "Cabbage" 
                | "Brussels Sprouts" 
                | "Carrot" 
                | "Beet" 
                | "Radish" 
                | "Turnip" 
                | "Onion" 
                | "Garlic" 
                | "Leek" 
                | "Shallot";